# Site settings
title: Cevo
email: sales@cevo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Cevo
  Software Consulting
  Devops
  Automation
  Infrastructure
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/cevoaustralia
linkedin_url: https://www.linkedin.com/company/cevoaustralia
youtube_url: https://www.youtube.com/channel/UCeWwnMuG8a93Y5jf3ak2HIw
melbourne_address: Level 14, 303 Collins St, Melbourne VIC 3000
sydney_address: Level 4, 20 Bond Street, Sydney NSW 2000

sales:
  phone: 1300 518 265
  email: sales@cevo.com.au

# Build settings
exclude: [Gemfile, Gemfile.lock, README.md, TODO.md]
markdown: kramdown
gems: [jekyll-paginate]
paginate: 4
paginate_path: "blog/page:num"
future: true
host: 0.0.0.0
